title: Блог Романичева
author: Vladimir Romanichev
email: vromanichev24@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Про программирование в целом и про программирование для ветеринарии в частности.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Vladimir Romanichev
  tagline: CTO Vetmanager, PHP Developer, Ironman 70.3
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: false # set to true to enable searchbar
  dark_mode: false # set to true to add dark mode toggle
  portfolio_image: "images/myphoto.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "ru" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  analytics_id: "G-QCBRS6MJQ7"
  disqus_shortname: "otis22-github-io"
  navigation:
    - title: About me
      url: "/about"
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    github:  otis22
    linkedIn: in/vladimir-romanichev-293b3967
    telegram: vromanichev
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #gitlab: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

#header_pages:
# - about.md

# Build settings
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
